export default function HomePage() {
  return (
      <main className="min-h-screen">
            <section className="bg-primary text-white py-20 px-4">
                    <div className="max-w-6xl mx-auto">
                              <h1 className="text-4xl font-bold mb-4">
                                          UGF Industrie
                                                    </h1>
                                                              <p className="text-xl mb-8">
                                                                          Votre partenaire B2B pour pièces industrielles et équipements
                                                                                    </p>
                                                                                              <div className="flex gap-4">
                                                                                                          <a
                                                                                                                        href="/catalogue"
                                                                                                                                      className="bg-secondary text-white px-8 py-3 rounded-lg font-semibold hover:opacity-90"
                                                                                                                                                  >
                                                                                                                                                                Voir le catalogue
                                                                                                                                                                            </a>
                                                                                                                                                                                        <a
                                                                                                                                                                                                      href="/register"
                                                                                                                                                                                                                    className="border border-white text-white px-8 py-3 rounded-lg font-semibold hover:bg-white hover:text-primary"
                                                                                                                                                                                                                                >
                                                                                                                                                                                                                                              Créer un compte
                                                                                                                                                                                                                                                          </a>
                                                                                                                                                                                                                                                                    </div>
                                                                                                                                                                                                                                                                            </div>
                                                                                                                                                                                                                                                                                  </section>
                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                        <section className="py-16 px-4 bg-gray-50">
                                                                                                                                                                                                                                                                                                <div className="max-w-6xl mx-auto">
                                                                                                                                                                                                                                                                                                          <h2 className="text-3xl font-bold text-center mb-12">
                                                                                                                                                                                                                                                                                                                      Pourquoi choisir UGF Industrie ?
                                                                                                                                                                                                                                                                                                                                </h2>
                                                                                                                                                                                                                                                                                                                                          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
                                                                                                                                                                                                                                                                                                                                                      <div className="bg-white p-6 rounded-lg shadow">
                                                                                                                                                                                                                                                                                                                                                                    <h3 className="text-xl font-semibold mb-3">Stock disponible</h3>
                                                                                                                                                                                                                                                                                                                                                                                  <p className="text-gray-600">Plus de 10 000 références en stock, livraison rapide partout en France.</p>
                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                          <div className="bg-white p-6 rounded-lg shadow">
                                                                                                                                                                                                                                                                                                                                                                                                                        <h3 className="text-xl font-semibold mb-3">Prix B2B</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                      <p className="text-gray-600">Tarifs professionnels et devis personnalisés pour les grosses commandes.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                              <div className="bg-white p-6 rounded-lg shadow">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <h3 className="text-xl font-semibold mb-3">Support expert</h3>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <p className="text-gray-600">Notre équipe technique vous accompagne dans vos projets industriels.</p>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              </section>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
